namespace MudBlazor.Components.QuickGrid;

/// <summary>
/// The unified request passed to the data pipeline for both client-side
/// (<c>IQueryable&lt;T&gt;</c>) and server-side (<c>GridItemsProvider&lt;T&gt;</c>) modes.
/// </summary>
/// <typeparam name="T">The grid row type.</typeparam>
public sealed record DataRequest<T>
{
    /// <summary>
    /// Gets or initialises the active sort instructions, ordered by <c>SortIndex</c> ascending.
    /// Applied after <see cref="GroupSortDefinitions"/> in the pipeline.
    /// </summary>
    public IReadOnlyList<SortDefinition<T>> SortDefinitions { get; init; } = [];

    /// <summary>
    /// Gets or initialises the group-pre-sort instructions generated by
    /// <c>IGridGroupingService&lt;T&gt;.ApplyGroupSort</c>.  These are prepended to the
    /// sort order to guarantee consecutive groups within paginated results.
    /// Server-side providers must honour these to maintain group consecutiveness.
    /// </summary>
    public IReadOnlyList<SortDefinition<T>> GroupSortDefinitions { get; init; } = [];

    /// <summary>Gets or initialises the active filter definitions.</summary>
    public IReadOnlyList<IFilterDefinition<T>> FilterDefinitions { get; init; } = [];

    /// <summary>
    /// Gets or initialises the optional quick-filter predicate.
    /// Applied in-memory after <see cref="FilterDefinitions"/>.
    /// <see langword="null"/> when no quick-filter string is active.
    /// </summary>
    public Func<T, bool>? QuickFilter { get; init; }

    /// <summary>
    /// Gets or initialises the zero-based index of the first item to return
    /// (i.e. <c>CurrentPage * RowsPerPage</c>).
    /// </summary>
    public int StartIndex { get; init; }

    /// <summary>
    /// Gets or initialises the maximum number of items to return (i.e. <c>RowsPerPage</c>).
    /// </summary>
    public int Count { get; init; }

    /// <summary>
    /// Gets or initialises the cancellation token supplied by the pipeline's debounce mechanism.
    /// Providers should respect this token to avoid redundant work on rapid state changes.
    /// </summary>
    public CancellationToken CancellationToken { get; init; }
}

/// <summary>
/// The data returned by the pipeline in response to a <see cref="DataRequest{T}"/>.
/// </summary>
/// <typeparam name="T">The grid row type.</typeparam>
public sealed record DataResponse<T>
{
    /// <summary>
    /// Gets or initialises the current page's items (or the full virtualized batch).
    /// </summary>
    public IReadOnlyList<T> Items { get; init; } = [];

    /// <summary>
    /// Gets or initialises the total number of items that match the active filters,
    /// <em>before</em> pagination is applied.  Used to compute <c>TotalPages</c>.
    /// </summary>
    public int TotalItemCount { get; init; }
}
